version: '3.9'

services:
    app-service:
        build: .
        container_name: perfume-shop
        volumes:
            - ./:/app
            - /app/node_modules
            - /app/.next
        ports:
            - 3000:3000
        environment:
            - NEXTAUTH_URL=http://localhost:3000/api/auth
            - NODE_ENV=development
        command: yarn dev
