import { useSession, signOut, signIn } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Autoplay, EffectFade, Navigation, Pagination, Scrollbar, A11y } from 'swiper';
import Link from 'next/link';
import Layout from '../components/Layout';
// import Products from '../components/Products';
import axios from 'axios';
import dynamic from 'next/dynamic';
import Loader from '../components/Loader';
import useSWR from 'swr';
const Products = dynamic(() => import('../components/Products'), { loading: () => <Loader /> });

export default function Home({ products }) {

  const { data: session } = useSession();
  const router = useRouter()

  const { data, error } = useSWR('/products', { fallbackData: products });

  return (
    <Layout>
      <Head>
        <title>Perfume Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Swiper
        modules={[Autoplay, EffectFade]}
        spaceBetween={30}
        slidesPerView={1}
        centeredSlides={true}
        navigation={false}
        effect={'fade'}
        autoplay={{
          "delay": 3400,
          "disableOnInteraction": false
        }}
        pagination={{ clickable: true }}
        scrollbar={{ draggable: true }}
        // onSwiper={(swiper) => console.log(swiper)}
        // onSlideChange={() => console.log('slide change')}
        className="mySwiper"
      >
        <SwiperSlide className="relative">
          <div className='absolute inset-0 flex z-20 justify-center items-center'>
            <div className='text-center'>
              <h3 className='text-base lg:text-3xl font-semibold text-white'>UP TO 70% OFF</h3>
              <h1 className='text-2xl lg:text-5xl text-white font-semibold'>Winter Restock Sale</h1>
              <h3 className='text-base lg:text-3xl text-white'>Replenish your supply on makeup, hair care and more.</h3>
            </div>
          </div>
          <div className='absolute inset-0 bg-black opacity-75 z-10' />
          <Image layout="intrinsic" className='absolute inset-0' height={820} width={1920} src="/perfume-1.jpg" alt="hero" />
        </SwiperSlide>
        <SwiperSlide className="relative">
          <div className='absolute inset-0 flex z-20 justify-center items-center'>
            <div className='text-center'>
              <h3 className='text-base lg:text-3xl font-semibold text-white'>UP TO 70% OFF</h3>
              <h1 className='text-2xl lg:text-5xl text-white font-semibold'>Winter Restock Sale</h1>
              <h3 className='text-base lg:text-3xl text-white'>Replenish your supply on makeup, hair care and more.</h3>
            </div>
          </div>
          <div className='absolute inset-0 bg-black opacity-75 z-10' />
          <Image layout="intrinsic" className='absolute inset-0' height={820} width={1920} src="/perfume-2.jpg" alt="hero" />
        </SwiperSlide>
        <SwiperSlide className="relative">
          <div className='absolute inset-0 flex z-20 justify-center items-center'>
            <div className='text-center'>
              <h3 className='text-base lg:text-3xl font-semibold text-white'>UP TO 70% OFF</h3>
              <h1 className='text-2xl lg:text-5xl text-white font-semibold'>Winter Restock Sale</h1>
              <h3 className='text-base lg:text-3xl text-white'>Replenish your supply on makeup, hair care and more.</h3>
            </div>
          </div>
          <div className='absolute inset-0 bg-black opacity-75 z-10' />
          <Image layout="intrinsic" className='absolute inset-0' height={820} width={1920} src="/perfume-3.jpg" alt="hero" />
        </SwiperSlide>
      </Swiper>

      {/* Top reviewed */}
      <div className='container mx-auto'>
        <Products heading="Top Reviewed" delay="5000" data={data} />
      </div>


      <section className='my-16'>
        <div className="container mx-auto">
          <Link href="/banner-1">
            <a className='w-full h-full flex justify-center items-center mb-10'>
              <Image className='intrinsic' src="/banner-1.jpg" height={450} width={1168} alt="banner-1" />
            </a>
          </Link>
        </div>
      </section>

      {/* Hot Sale */}
      <div className='container mx-auto'>
        <Products className="container mx-auto" heading="Hot Sale" delay="4500" data={data} />
      </div>

      {/* banner section */}
      <section className='my-16'>
        <div className="container mx-auto">
          <Link href="/banner-1">
            <a className='w-full h-full flex justify-center items-center mb-10'>
              <Image className='intrinsic' src="/banner-2.jpg" height={450} width={1168} alt="banner-2" />
            </a>
          </Link>
        </div>
      </section>

      {/* blog section */}
      <section className='my-16'>
        <div className="container mx-auto">
          <h1 className='text-xl lg:text-3xl font-semibold text-center mb-5'>From Our Blog</h1>
          <Swiper
            modules={[Autoplay, Pagination, Navigation]}
            spaceBetween={10}
            autoplay={{
              "delay": 4400,
              "disableOnInteraction": false
            }}
            loop={true}
            centeredSlides={true}
            // onSlideChange={() => console.log('slide change')}
            // onSwiper={(swiper) => console.log(swiper)}
            breakpoints={{
              640: {
                width: 640,
                slidesPerView: 1
              },
              768: {
                width: 768,
                slidesPerView: 2,
              },
              992: {
                width: 992,
                slidesPerView: 3,
              },
              1200: {
                width: 1200,
                slidesPerView: 4,
              },
            }}
            className="mySwiper"
          >
            <SwiperSlide className="flex justify-center items-center h-full">
              <div className='w-full h-full'>
                <div className='flex justify-center items-center'>
                  <Image className="scale-100 hover:scale-110 normal-transition" layout='intrinsic' height={497} width={468} alt="category-1" src="/blog-1.jpg" />
                </div>
                <div className="text-center">
                  <div className='flex flex-col'>
                    <span className="text-base text-gray-500 mt-4 normal-transition">January 6, 2022</span>
                    <span className='text-xl font-semibold text-gray-500 normal-transition'>Rules For Press-On Nails</span>
                  </div>
                  <Link href="/123">
                    <a className='flex justify-center items-center w-1/2 mx-auto mt-3 hover:bg-purple-600 text-white normal-transition
                   bg-purple-800 px-4 py-2'>Read More</a>
                  </Link>
                </div>
              </div>
            </SwiperSlide>

            <SwiperSlide className="flex justify-center items-center h-full">
              <div className='w-full h-full'>
                <div className='flex justify-center items-center'>
                  <Image className="scale-100 hover:scale-110 normal-transition" layout='intrinsic' height={497} width={468} alt="category-1" src="/blog-2.jpg" />
                </div>
                <div className="text-center">
                  <div className='flex flex-col'>
                    <span className="text-base text-gray-500 mt-4 normal-transition">January 6, 2022</span>
                    <span className='text-xl font-semibold text-gray-500 normal-transition'>Rules For Press-On Nails</span>
                  </div>
                  <Link href="/123">
                    <a className='flex justify-center items-center w-1/2 mx-auto mt-3 hover:bg-purple-600 text-white normal-transition
                   bg-purple-800 px-4 py-2'>Read More</a>
                  </Link>
                </div>
              </div>
            </SwiperSlide>

            <SwiperSlide className="flex justify-center items-center h-full">
              <div className='w-full h-full'>
                <div className='flex justify-center items-center'>
                  <Image className="scale-100 hover:scale-110 normal-transition" layout='intrinsic' height={497} width={468} alt="category-1" src="/blog-3.jpg" />
                </div>
                <div className="text-center">
                  <div className='flex flex-col'>
                    <span className="text-base text-gray-500 mt-4 normal-transition">January 6, 2022</span>
                    <span className='text-xl font-semibold text-gray-500 normal-transition'>Rules For Press-On Nails</span>
                  </div>
                  <Link href="/123">
                    <a className='flex justify-center items-center w-1/2 mx-auto mt-3 hover:bg-purple-600 text-white normal-transition
                   bg-purple-800 px-4 py-2'>Read More</a>
                  </Link>
                </div>
              </div>
            </SwiperSlide>

            <SwiperSlide className="flex justify-center items-center h-full">
              <div className='w-full h-full'>
                <div className='flex justify-center items-center'>
                  <Image className="scale-100 hover:scale-110 normal-transition" layout='intrinsic' height={497} width={468} alt="category-1" src="/blog-4.jpg" />
                </div>
                <div className="text-center">
                  <div className='flex flex-col'>
                    <span className="text-base text-gray-500 mt-4 normal-transition">January 6, 2022</span>
                    <span className='text-xl font-semibold text-gray-500 normal-transition'>Rules For Press-On Nails</span>
                  </div>
                  <Link href="/123">
                    <a className='flex justify-center items-center w-1/2 mx-auto mt-3 hover:bg-purple-600 text-white normal-transition
                   bg-purple-800 px-4 py-2'>Read More</a>
                  </Link>
                </div>
              </div>
            </SwiperSlide>
          </Swiper>
        </div>
      </section>
    </Layout>
  )
}

export async function getServerSideProps() {
  // Fetch data from external API
  const { data } = await axios.get('/products')
  // Pass data to the page via props
  return { props: { products: data } }
}