export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_PRODUCT_FROM_CART = 'GET_PRODUCT_FROM_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const ERROR_WHILE_CART_ACTION = 'ERROR_WHILE_CART_ACTION';
export const CLEAR_CART = 'CLEAR_CART';